### ISSUE TITLE
Archive repo

### ISSUE THREAD

**Issue by tbeck** [sethburtonhall/artist-rescue-trust#6]
We have migrated to a new SSG/CMS combo. Here is the repo: https://github.com/ocupop/artist-rescue

Can we archive this repo and point to new one?
Thanks!

**Comment by adrianbg** [comment]
I'm with Kettle. Not sure you two have access, but if you confirm, I can archive this repository.

**Comment by tbeck** [comment]
Hi @adrianbg - Thanks for your help. It would be great to archive this repo since the live site has been migrated. I don't have permissions on this end, but let me know if you need anything from me (Ocupop).

**Comment by adrianbg** [comment]
Sounds good. I just wanted to be completely sure before I archived it because I'm out of touch with this repo.

**Comment by adrianbg** [comment]
I was about to archive it, then GitHub recommended a couple of pre-archival tasks. Do you want to do this stuff or should I just archive it?
- Closing all open issues and pull requests
- Making a note in your README

**Comment by tbeck** [comment]
Thanks @adrianbg - I have pushed those pre-archival changes and I think that we are ready.
